// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Os5lHZqiaRRdBsZm1cO1JsX7sdrYgk0',
    appId: '1:230162719736:web:9160e32815ca50a230ac0d',
    messagingSenderId: '230162719736',
    projectId: 'study-76861',
    authDomain: 'study-76861.firebaseapp.com',
    storageBucket: 'study-76861.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvAGiD1GDhb_iQyNJRYE5XDw3en0w99RQ',
    appId: '1:230162719736:ios:4bfd4016323a17d730ac0d',
    messagingSenderId: '230162719736',
    projectId: 'study-76861',
    storageBucket: 'study-76861.firebasestorage.app',
    iosBundleId: 'com.example.saarthi2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Os5lHZqiaRRdBsZm1cO1JsX7sdrYgk0',
    appId: '1:230162719736:web:26279398503bca4730ac0d',
    messagingSenderId: '230162719736',
    projectId: 'study-76861',
    authDomain: 'study-76861.firebaseapp.com',
    storageBucket: 'study-76861.firebasestorage.app',
  );
}
